<%@ Page Title="" Language="C#" MasterPageFile="~/musicvalley.master" AutoEventWireup="true" CodeFile="cart.aspx.cs" Inherits="Default3" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <table style="width: 100%; height: 694px;">
        <tr>
            <td>
                <div style="height: 686px">
                    <table style="width: 100%; height: 686px;">
                        <tr>
                            <td style="height: 49px; font-family: Calibri; font-size: large; text-transform: uppercase; text-align: center; color: #000000;">
                                <div>
                                    <span style="color: #FF0000">&nbsp;</span><strong><span style="color: #FF0000">&lt;&lt;</span>
                                    <span style="color: #0000FF">SHOPPING CART</span> <span style="color: #FF0000">&gt;&gt;</span><span style="color: #FFFFFF">&gt;</span></strong></div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div style="height: 632px">
                                    <table style="width: 100%; height: 593px;">
                                        <tr>
                                            <td>
                                                <div style="height: 287px">
                                                    <table style="width: 100%; height: 290px;">
                                                        <tr>
                                                            <td class="style25" style="width: 536px">
                                                                <div style="font-family: Calibri; font-size: small; height: 287px; width: 552px; font: 100% Calibri; text-transform: uppercase; text-align: left; color: #00FF00; font-weight: normal;">
        <asp:GridView ID="GridView1" runat="server" BackColor="White" 
            BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="4" 
            ForeColor="Black" GridLines="Horizontal" 
             
            AutoGenerateDeleteButton="True" onrowdeleting="GridView1_RowDeleting" 
            AllowPaging="True" AllowSorting="True" Font-Bold="True" Font-Names="Calibri" 
            Font-Overline="False" Font-Size="Large" DataKeyNames="cartID" PageSize="5" Height="288px" 
                                                                        onpageindexchanging="GridView1_PageIndexChanging" Width="550px">
            <EmptyDataTemplate>
                NO PRODUCT ADDED TO CART
            </EmptyDataTemplate>
            <FooterStyle BackColor="#CCCC99" ForeColor="Black" />
            <HeaderStyle BackColor="#333333" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="White" ForeColor="Black" HorizontalAlign="Right" />
            <SelectedRowStyle BackColor="#CC3333" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F7F7F7" />
            <SortedAscendingHeaderStyle BackColor="#4B4B4B" />
            <SortedDescendingCellStyle BackColor="#E5E5E5" />
            <SortedDescendingHeaderStyle BackColor="#242121" />
        </asp:GridView>
                                                                </div>
                                                            </td>
                                                            <td>
                                                                <div style="border: thin #000000 dotted; height: 286px; font-family: Calibri; font-size: medium; text-transform: uppercase; text-align: center;">
                                                                    <table style="width:100%;">
                                                                        <tr>
                                                                            <td>
                                                                                <strong>BILL&nbsp; INFORMATION</strong></td>
                                                                        </tr>
                                                                        <tr>
                                                                            <td>
                                                                                &nbsp;</td>
                                                                        </tr>
                                                                        <tr>
                                                                            <td>
                                                                                &nbsp;</td>
                                                                        </tr>
                                                                        <tr>
                                                                            <td>
                                                                                &nbsp;total items <strong>:</strong>&nbsp;<asp:Label ID="Label4" runat="server" 
                                                                                    Text="Label" style="color: #0000FF; font-weight: 700"></asp:Label>
                                                                            </td>
                                                                        </tr>
                                                                        <tr>
                                                                            <td>
                                                                                total bill AMOUNT <strong>:</strong> $
        <asp:Label ID="Label3" runat="server" Text="Label" style="color: #FF0000; font-weight: 700"></asp:Label>
                                                                            </td>
                                                                        </tr>
                                                                        <tr>
                                                                            <td>
                                                                                &nbsp;</td>
                                                                        </tr>
                                                                        <tr>
                                                                            <td>
        <asp:HyperLink ID="HyperLink18" runat="server" 
                    NavigateUrl="~/home.aspx">CONTINUE SHOPPING</asp:HyperLink>
                                                                            </td>
                                                                        </tr>
                                                                        <tr>
                                                                            <td style="height: 27px">
        &nbsp;<asp:LinkButton ID="LinkButton18" runat="server" Font-Size="Smaller" 
                                                                                    onclick="LinkButton18_Click">change shipping address</asp:LinkButton>
                                                                                &nbsp;&nbsp;</td>
                                                                        </tr>
                                                                        <tr>
                                                                            <td>
                                                                                &nbsp;</td>
                                                                        </tr>
                                                                        <tr>
                                                                            <td>
                                                                                <asp:Button ID="Button4" runat="server" onclick="Button4_Click" 
                                                                                    Text="MODE OF PAYMENT" Width="271px" />
                                                                            </td>
                                                                        </tr>
                                                                        <tr>
                                                                            <td>
                                                                                <asp:Label ID="Label5" runat="server" 
                                                                                    style="font-weight: 700; font-size: small; color: #FF0000" Text="Label"></asp:Label>
                                                                            </td>
                                                                        </tr>
                                                                    </table>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    </table>
&nbsp;&nbsp;&nbsp;
                                                </div>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <div style="height: 336px">
                                                    <asp:Panel ID="Panel4" runat="server" Height="337px" Visible="False">
                                                        <div  id="mode" 
    style="border: thin #000000 dotted; height: 337px; font-family: Calibri;">
                                                            <span style="font-family: Calibri; color: #FF0000; text-align: center"><strong>
                                                            WELCOME TO PAYMENT GATEWAY </strong></span>
                                                            <br />
                                                            <br />
                                                            <asp:RadioButton ID="RadioButton1" runat="server" AutoPostBack="True" 
                                                                BackColor="Black" ForeColor="White" GroupName="mode" 
                                                                oncheckedchanged="RadioButton1_CheckedChanged" 
                                                                style="font-weight: 700; font-family: Calibri; font-size: large" 
                                                                Text="NET BANKING " Width="855px" BorderColor="White" BorderStyle="Dotted" 
                                                                BorderWidth="1px" />
                                                            <asp:Panel ID="Panel1" runat="server" BackColor="#CCFFFF" Height="185px" 
                                                                Visible="False">
                                                                <table style="width:100%;">
                                                                    <tr>
                                                                        <td colspan="2" style="color: #0000CC">
                                                                            <strong>PAYMENT INFORMATION</strong></td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td colspan="2">
                                                                            &nbsp;</td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td class="style29" style="width: 233px">
                                                                            CARD NUMBER
                                                                        </td>
                                                                        <td>
                                                                            <asp:TextBox ID="TextBox2" runat="server" Width="145px"></asp:TextBox>
                                                                            <asp:RequiredFieldValidator ID="RequiredFieldValidator4" runat="server" 
                                                                                ControlToValidate="TextBox2" ErrorMessage="* missing" 
                                                                                style="font-size: small; color: #FF0000" ValidationGroup="pay1"></asp:RequiredFieldValidator>
                                                                            <asp:CompareValidator ID="CompareValidator1" runat="server" 
                                                                                ControlToValidate="TextBox2" ErrorMessage="numeric only" 
                                                                                Operator="DataTypeCheck" style="font-size: small; color: #FF0000" Type="Double" 
                                                                                ValidationGroup="pay1"></asp:CompareValidator>
                                                                            <asp:RegularExpressionValidator ID="RegularExpressionValidator1" runat="server" 
                                                                                ControlToValidate="TextBox2" ErrorMessage="16 digits required" 
                                                                                style="color: #FF0000; font-size: small" ValidationExpression="\d{16}" 
                                                                                ValidationGroup="pay1"></asp:RegularExpressionValidator>
                                                                        </td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td class="style29" style="width: 233px">
                                                                            EXPIRY DATE
                                                                        </td>
                                                                        <td>
                                                                            <asp:DropDownList ID="DropDownList1" runat="server" Height="25px" Width="50px">
                                                                                <asp:ListItem>1</asp:ListItem>
                                                                                <asp:ListItem>2</asp:ListItem>
                                                                                <asp:ListItem>3</asp:ListItem>
                                                                                <asp:ListItem>4</asp:ListItem>
                                                                                <asp:ListItem>5</asp:ListItem>
                                                                                <asp:ListItem>5</asp:ListItem>
                                                                                <asp:ListItem>6</asp:ListItem>
                                                                                <asp:ListItem>7</asp:ListItem>
                                                                                <asp:ListItem>8</asp:ListItem>
                                                                                <asp:ListItem>9</asp:ListItem>
                                                                                <asp:ListItem>10</asp:ListItem>
                                                                                <asp:ListItem>11</asp:ListItem>
                                                                                <asp:ListItem>12</asp:ListItem>
                                                                            </asp:DropDownList>
                                                                            <asp:DropDownList ID="DropDownList2" runat="server" Height="25px" Width="60px">
                                                                                <asp:ListItem>2011</asp:ListItem>
                                                                                <asp:ListItem>2012</asp:ListItem>
                                                                                <asp:ListItem>2013</asp:ListItem>
                                                                                <asp:ListItem>2014</asp:ListItem>
                                                                                <asp:ListItem>2015</asp:ListItem>
                                                                                <asp:ListItem>2016</asp:ListItem>
                                                                                <asp:ListItem>2017</asp:ListItem>
                                                                                <asp:ListItem>2018</asp:ListItem>
                                                                                <asp:ListItem>2019</asp:ListItem>
                                                                                <asp:ListItem>2020</asp:ListItem>
                                                                            </asp:DropDownList>
                                                                        </td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td class="style29" style="width: 233px">
                                                                            INTERNET PASSWORD(IPIN)
                                                                        </td>
                                                                        <td>
                                                                            <asp:TextBox ID="TextBox3" runat="server" Width="90px"></asp:TextBox>
                                                                            <asp:RequiredFieldValidator ID="RequiredFieldValidator5" runat="server" 
                                                                                ControlToValidate="TextBox3" ErrorMessage="* missing" 
                                                                                style="font-size: small; color: #FF0000" ValidationGroup="pay1"></asp:RequiredFieldValidator>
                                                                            <asp:CompareValidator ID="CompareValidator2" runat="server" 
                                                                                ControlToValidate="TextBox3" ErrorMessage="numeric only" 
                                                                                Operator="DataTypeCheck" style="color: #FF0000; font-size: small" 
                                                                                Type="Integer" ValidationGroup="pay1"></asp:CompareValidator>
                                                                            <asp:RegularExpressionValidator ID="RegularExpressionValidator3" runat="server" 
                                                                                ControlToValidate="TextBox3" ErrorMessage="4 digits required" 
                                                                                style="color: #FF0000; font-size: small" ValidationExpression="\d{4}" 
                                                                                ValidationGroup="pay1"></asp:RegularExpressionValidator>
                                                                        </td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td colspan="2">
                                                                            &nbsp;</td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td colspan="2">
                                                                            <asp:Button ID="Button3" runat="server" Font-Bold="True" Font-Names="Calibri" 
                                                                                ForeColor="#0000CC" onclick="Button3_Click" Text="PROCEED TO CHECKOUT" 
                                                                                ValidationGroup="pay1" />
                                                                        </td>
                                                                    </tr>
                                                                </table>
                                                                <br />
                                                                <br />
                                                            </asp:Panel>
                                                            <asp:RadioButton ID="RadioButton2" runat="server" AutoPostBack="True" 
                                                                BackColor="Black" Font-Bold="True" Font-Names="Calibri" Font-Size="Large" 
                                                                ForeColor="White" GroupName="mode" 
                                                                oncheckedchanged="RadioButton2_CheckedChanged" Text="CREDIT CARD" 
                                                                Width="855px" BorderColor="White" BorderStyle="Dotted" BorderWidth="1px" />
                                                            <asp:Panel ID="Panel2" runat="server" BackColor="#CCFFFF" Height="211px" 
                                                                Visible="False">
                                                                <table style="width:100%;">
                                                                    <tr>
                                                                        <td colspan="2" style="color: #0000CC">
                                                                            <strong>PAYMENT INFORMATION</strong></td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td colspan="2">
                                                                            &nbsp;</td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td style="width: 235px">
                                                                            CARD NUMBER
                                                                        </td>
                                                                        <td>
                                                                            <asp:TextBox ID="TextBox4" runat="server" Width="147px"></asp:TextBox>
                                                                            <asp:RequiredFieldValidator ID="RequiredFieldValidator6" runat="server" 
                                                                                ControlToValidate="TextBox4" ErrorMessage="* missing" 
                                                                                style="font-size: small; color: #FF0000" ValidationGroup="pay2"></asp:RequiredFieldValidator>
                                                                            <asp:CompareValidator ID="CompareValidator3" runat="server" 
                                                                                ControlToValidate="TextBox4" ErrorMessage="numeric only" 
                                                                                Operator="DataTypeCheck" style="font-size: small; color: #FF0000" Type="Double" 
                                                                                ValidationGroup="pay2"></asp:CompareValidator>
                                                                            <asp:RegularExpressionValidator ID="RegularExpressionValidator4" runat="server" 
                                                                                ControlToValidate="TextBox4" ErrorMessage="19 digits required" 
                                                                                style="font-size: small; color: #FF0000" ValidationExpression="\d{19}" 
                                                                                ValidationGroup="pay2"></asp:RegularExpressionValidator>
                                                                        </td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td style="width: 235px">
                                                                            CVV NUMBER
                                                                        </td>
                                                                        <td>
                                                                            <asp:TextBox ID="TextBox5" runat="server" Width="94px"></asp:TextBox>
                                                                            <asp:RequiredFieldValidator ID="RequiredFieldValidator7" runat="server" 
                                                                                ControlToValidate="TextBox5" ErrorMessage="* missing" 
                                                                                style="font-size: small; color: #FF0000" ValidationGroup="pay2"></asp:RequiredFieldValidator>
                                                                            <asp:CompareValidator ID="CompareValidator4" runat="server" 
                                                                                ControlToValidate="TextBox5" ErrorMessage="numeric only" 
                                                                                Operator="DataTypeCheck" style="font-size: small; color: #FF0000" 
                                                                                Type="Integer" ValidationGroup="pay2"></asp:CompareValidator>
                                                                            <asp:RegularExpressionValidator ID="RegularExpressionValidator6" runat="server" 
                                                                                ControlToValidate="TextBox5" ErrorMessage="3 digit required" 
                                                                                style="font-size: small; color: #FF0000" ValidationExpression="\d{3}" 
                                                                                ValidationGroup="pay2"></asp:RegularExpressionValidator>
                                                                        </td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td style="width: 235px">
                                                                            EXPIRY DATE
                                                                        </td>
                                                                        <td>
                                                                            <asp:DropDownList ID="DropDownList3" runat="server" Height="25px" Width="50px">
                                                                                <asp:ListItem>1</asp:ListItem>
                                                                                <asp:ListItem>2</asp:ListItem>
                                                                                <asp:ListItem>3</asp:ListItem>
                                                                                <asp:ListItem>4</asp:ListItem>
                                                                                <asp:ListItem>5</asp:ListItem>
                                                                                <asp:ListItem>5</asp:ListItem>
                                                                                <asp:ListItem>6</asp:ListItem>
                                                                                <asp:ListItem>7</asp:ListItem>
                                                                                <asp:ListItem>8</asp:ListItem>
                                                                                <asp:ListItem>9</asp:ListItem>
                                                                                <asp:ListItem>10</asp:ListItem>
                                                                                <asp:ListItem>11</asp:ListItem>
                                                                                <asp:ListItem>12</asp:ListItem>
                                                                            </asp:DropDownList>
                                                                            <asp:DropDownList ID="DropDownList4" runat="server" Height="25px" Width="60px">
                                                                                <asp:ListItem>2011</asp:ListItem>
                                                                                <asp:ListItem>2012</asp:ListItem>
                                                                                <asp:ListItem>2013</asp:ListItem>
                                                                                <asp:ListItem>2014</asp:ListItem>
                                                                                <asp:ListItem>2015</asp:ListItem>
                                                                                <asp:ListItem>2016</asp:ListItem>
                                                                                <asp:ListItem>2017</asp:ListItem>
                                                                                <asp:ListItem>2018</asp:ListItem>
                                                                                <asp:ListItem>2019</asp:ListItem>
                                                                                <asp:ListItem>2020</asp:ListItem>
                                                                            </asp:DropDownList>
                                                                        </td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td style="width: 235px">
                                                                            CARD HOLDER NAME
                                                                        </td>
                                                                        <td>
                                                                            <asp:TextBox ID="TextBox6" runat="server" Width="92px"></asp:TextBox>
                                                                            <asp:RequiredFieldValidator ID="RequiredFieldValidator8" runat="server" 
                                                                                ControlToValidate="TextBox6" ErrorMessage="* missing" 
                                                                                style="color: #FF0000; font-size: small" ValidationGroup="pay2"></asp:RequiredFieldValidator>
                                                                            <asp:CompareValidator ID="CompareValidator5" runat="server" 
                                                                                ControlToValidate="TextBox6" ErrorMessage="alphabets only" 
                                                                                Operator="DataTypeCheck" style="font-size: small; color: #FF0000" 
                                                                                ValidationGroup="pay2"></asp:CompareValidator>
                                                                        </td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td colspan="2">
                                                                            &nbsp;</td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td colspan="2">
                                                                            <asp:Button ID="Button5" runat="server" Font-Bold="True" Font-Names="Calibri" 
                                                                                ForeColor="#0000CC" onclick="Button5_Click" Text="PROCEED TO CHECKOUT" 
                                                                                ValidationGroup="pay2" />
                                                                        </td>
                                                                    </tr>
                                                                </table>
                                                            </asp:Panel>
                                                            <asp:RadioButton ID="RadioButton3" runat="server" AutoPostBack="True" 
                                                                BackColor="Black" Font-Bold="True" Font-Names="Calibri" Font-Size="Large" 
                                                                ForeColor="White" GroupName="mode" 
                                                                oncheckedchanged="RadioButton3_CheckedChanged" Text="CASH ON DELEIVERY" 
                                                                Width="855px" BorderColor="White" BorderStyle="Dotted" BorderWidth="1px" />
                                                            <asp:Panel ID="Panel3" runat="server" BackColor="#CCFFFF" Visible="False" 
                                                                Height="54px">
                                                                <table style="width:100%;">
                                                                    <tr>
                                                                        <td>
                                                                            &nbsp;</td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td>
                                                                            <asp:Button ID="Button6" runat="server" Font-Bold="True" Font-Names="Calibri" 
                                                                                ForeColor="#0000CC" onclick="Button6_Click" Text="PROCEED TO CHECKOUT" />
                                                                        </td>
                                                                    </tr>
                                                                </table>
                                                            </asp:Panel>
                                                            <br />
&nbsp;</div>
                                                    </asp:Panel>

                                                    <asp:Panel ID="Panel5" runat="server" Height="338px" Visible="False">
                                                        <span style="font-family: Calibri; color: #FF0000"><strong>
                                                        <br />
                                                        <span style="font-size: x-large">YOU ARE NOT A REGISTERED MEMBER ???</span></strong></span><br />
                                                        <br />
                                                        <strong><span style="font-family: Calibri"><span style="color: #FF0000">&gt;&gt;</span>
                                                        </span>
                                                        <asp:LinkButton ID="LinkButton21" runat="server" onclick="LinkButton19_Click" 
                                                            style="font-family: Calibri; font-size: large; text-decoration: blink">LOGIN</asp:LinkButton>
                                                        <span style="font-family: Calibri; font-size: large">&nbsp;WITH YOUR USERNAME</span><span 
                                                            style="font-family: Calibri">&nbsp; </span></strong>
                                                        <br />
                                                        <br />
                                                        <span style="font-family: Calibri; font-size: large"><strong>
                                                        <span style="color: #FF0000">&gt;&gt;</span> </strong></span><strong>
                                                        <asp:LinkButton ID="LinkButton22" runat="server" onclick="LinkButton20_Click" 
                                                            style="font-family: Calibri; font-size: large; text-decoration: blink">REGISTER</asp:LinkButton>
                                                        </strong><span style="font-family: Calibri; font-size: large"><strong>&nbsp;A NEW 
                                                        ACCOUNT </strong></span>
                                                    </asp:Panel>

                                                </div>
                                               

                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                &nbsp;</td>
                                        </tr>
                                        <tr>
                                            <td>
                                                &nbsp;</td>
                                        </tr>
                                    </table>
                                </div>
                            </td>
                        </tr>
                    </table>
                </div>
            </td>
        </tr>
    </table>
</asp:Content>

